slug = "exceptions/easy/safe_index/problem_001"
title = "Safe index"
topic = "exceptions"
difficulty = "easy"

prompt = """
Write `safe_index(xs, i)` that returns `xs[i]` or `None` if it's out of range.
"""

starter_code = """
def safe_index(xs, i):
    # TODO
    pass
"""

tests = """
assert safe_index([3, 2, 6, 7, 7], 0) == 3
"""
